3 cls
5 ?:?"   Berechnung des Klassendurchschnitts"
10 ?:?:input"   Wie viele Schler haben eine 1";e
20 input"   Wie viele Schler haben eine 2";z
30 input"   Wie viele Schler haben eine 3";d
40 input"   Wie viele Schler haben eine 4";v
50 input"   Wie viele Schler haben eine 5";f
60 input"   Wie viele Schler haben eine 6";s
70 g=e+z+d+v+f+s
80 x=(e*1+z*2+d*3+v*4+f*5+s*6)/g
90 ?:?"   Die Durchschnittszensur des Tests betr„gt:";x
100 end