10 cls
20 ?:?:?:?:?:?:?:?:?
30 ?"                   Hallo Simon !"
40 ?"   Wie geht es Dir ? Ich hoffe, Deine schulischen Erfolge sind wie zuvor."
50 ?"   Da das Schuljahr jetzt zuende geht, kann ich Dir ja noch etwas ver - "
60 ?"   raten, Du wolltest Dich ja intellektuell mit Klaus Sievers auseinan -"
70 ?"   setzen. Ein Programm, von dem ich wei·, da· er es nicht auf legale "
80 ?"   Weise erworben hat, ist das PC Route. Aber Du wirst, denke ich, ange -"
90 ?"   messen reagieren, daher also Deine Informationsquelle verschleiern."
100 ?"   Ansonsten gibt es nix Neues, ich habe sehr gro·en Spa· an dem PC -"
110 ?"   Cosmos von Dir. Wenn Du einige vernÅnftige Spiele hast, bitte ich,"
120 ?"   mir eine Kopie zu machen. Ansonsten grÅ·e bitte ganz besonders H.G."
130 ?"   das sagten wir immer frÅher, wenn Du nicht merken solltest, worum "
140 ?"   es geht, ich meine Hans GÅnther. Also, bis bald mal .... Tom"
145 ?:?:?:?:?:?"         DrÅcken Sie eine Taste....."
150 x$=inkey$:if x$="" then 150
160 cls
170 ?:?:?:?:?:?:?:?"   Nun wird Ihre Festplatte neu formatiert..."
180 ?"   Damit alle Raubkopien gelîscht werden!."
185 ?"   Mal sehen, was da so drauf ist...
187 for t=1 to 9000 : next t
190 shell "c:"
200 shell "DIR/W"
205 shell "a:"
207 cls
210 ?:?:?:?"   Sie haben GlÅck, heute wird nichts gelîscht!!!!"
230 end